import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime, timedelta
import time
import numpy as np

"""
Market Analysis Terminal - Streamlit Interactive Visualization.

This module serves as the frontend for the Strategic Intelligence System.
It loads historical and real-time data from the HDF5 store (generated by spider.py)
and renders an interactive dashboard using Streamlit and Plotly.

Usage:
    Ensure 'market_data.h5' exists (run spider.py first).
    Run with: streamlit run stream.py
"""
# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Market Analysis Terminal",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- CSS STYLING ---
st.markdown("""
<style>
    .metric-card {
        background-color: #0E1117;
        border: 1px solid #262730;
        border-radius: 5px;
        padding: 15px;
        text-align: center;
    }
    .stMetric {
        background-color: transparent !important;
    }
    h1, h2, h3 {
        font-family: 'Helvetica Neue', sans-serif;
    }
</style>
""", unsafe_allow_html=True)

# --- CONFIGURATION ---
HDF5_FILE = "market_data.h5"
REFRESH_RATE = 30  # Auto-refresh seconds

# --- DATA LOADING ENGINE ---
@st.cache_data(ttl=15)  # Cache data for 15 seconds to prevent disk thrashing
def load_market_data():
   """
    Load and unify market data from the local HDF5 storage.

    Reads distinct data groups (history, stocks, news, macro) from the HDF5 file
    and merges them into normalized DataFrames for the dashboard.

    Returns:
        tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]: A tuple containing:
            - df_prices: Unified historical and real-time stock prices.
            - df_news: Aggregated news headlines and sentiment scores.
            - df_macro: Commodity and macro-economic indicators.
    """
    try:
        frames = []
        # We read these specific keys from the HDF5 store
        keys_to_check = ['/history', '/stocks', '/news', '/macro', '/fundamentals']
        
        with pd.HDFStore(HDF5_FILE, mode='r') as store:
            available_keys = store.keys()
            
            # Load History & Real-time Stocks
            if '/history' in available_keys:
                frames.append(store['/history'])
            if '/stocks' in available_keys:
                frames.append(store['/stocks'])
            
            # Load News & Sentiment
            if '/news' in available_keys:
                frames.append(store['/news'])
            
            # Load Macro Data
            if '/macro' in available_keys:
                frames.append(store['/macro'])

        if not frames:
            return pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

        # Combine main data
        master_df = pd.concat(frames, ignore_index=True)
        
        # Standardization
        if 'date' in master_df.columns:
            # FIX: Normalize to midnight (removes hours/minutes) to make bars wide
            master_df['date'] = pd.to_datetime(master_df['date']).dt.normalize()
        
        # Split back into logical groups for the dashboard
        df_prices = master_df[master_df['type'].isin(['History', 'Stock', 'stock_finviz'])].copy()
        df_news = master_df[master_df['type'].isin(['News', 'news_finviz', 'news_marketwatch', 'news_energy'])].copy()
        df_macro = master_df[master_df['type'] == 'commodity'].copy()
        
        return df_prices, df_news, df_macro

    except FileNotFoundError:
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame()
    except Exception as e:
        st.error(f"Data Engine Error: {e}")
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

# --- DASHBOARD LOGIC ---
def main():
    """
    Main execution loop for the Streamlit dashboard.

    Sets up the application layout, initializes the auto-refresh loop,
    and renders the following components:
    - Sidebar controls (Ticker selection, Date filter).
    - KPI Metrics (Price, Sentiment, Volume).
    - Interactive Tabs (Charts, Sentiment Analysis, Macro View).
    - Real-time News Feed and Data Inspector.
    """
    st.title("Market Analysis Terminal")
    st.markdown(f"**System Status:** 🟢 Online | **Source:** `{HDF5_FILE}` | **Refresh:** {REFRESH_RATE}s")
    
    main_container = st.empty()
    while True:
        # Load fresh data
        df_prices, df_news, df_macro = load_market_data()

        with main_container.container():
            if df_prices.empty and df_news.empty:
                st.warning("⚠️ Waiting for Spider... No data found yet.")
                st.info("Run `python spider.py` in your terminal to start collecting data.")
                time.sleep(5)
                continue

            # --- SIDEBAR CONTROLS ---
            with st.sidebar:
                st.header("⚙️ Control Panel")
                
                # Ticker Selection
                all_tickers = sorted(list(set(df_prices['ticker'].unique()) | set(df_news['ticker'].unique())))
                if not all_tickers: all_tickers = ["WAITING..."]
                
                selected_ticker = st.selectbox("Select Asset", all_tickers, index=0)
                
                # Date Range
                min_date = df_prices['date'].min() if not df_prices.empty else datetime.now()
                max_date = datetime.now()
                
                date_range = st.date_input(
                    "Date Filter",
                    value=(min_date, max_date),
                    min_value=min_date,
                    max_value=max_date
                )

                st.markdown("---")
                st.markdown("### 📊 View Settings")
                show_volume = st.checkbox("Show Volume", value=True)
                show_ma = st.checkbox("Show Moving Averages", value=True)
                
                st.markdown("---")
                st.caption("Market Analysis Terminal")

            # --- FILTERING DATA ---
            # Filter by Date
            mask_start = pd.Timestamp(date_range[0])
            mask_end = pd.Timestamp(date_range[1]) + timedelta(days=1)
            
            ticker_prices = df_prices[
                (df_prices['ticker'] == selected_ticker) & 
                (df_prices['date'] >= mask_start) & 
                (df_prices['date'] <= mask_end)
            ].sort_values('date')

            # --- FIX: Clean Anomalies (Remove Bad "0" Values) ---
            # This cancels the "extremely long" candle caused by bad scraping
            ticker_prices = ticker_prices[
                (ticker_prices['high'] > 0.1) & 
                (ticker_prices['low'] > 0.1)
            ]

            # --- Ensure Zoom ---
            if len(ticker_prices) > 30:
                ticker_prices = ticker_prices.tail(30)

            ticker_news = df_news[
                (df_news['ticker'] == selected_ticker) &
                (df_news['date'] >= mask_start) & 
                (df_news['date'] <= mask_end)
            ].sort_values('date', ascending=False)

            # --- TOP KPI ROW ---
            st.markdown("### 🏛️ Executive Summary")
            kpi1, kpi2, kpi3, kpi4 = st.columns(4)

            # KPI 1: Latest Price
            if not ticker_prices.empty:
                latest = ticker_prices.iloc[-1]
                prev = ticker_prices.iloc[-2] if len(ticker_prices) > 1 else latest
                
                price_val = latest['close']
                delta = price_val - prev['close']
                delta_pct = (delta / prev['close']) * 100
                
                kpi1.metric("Last Price", f"${price_val:,.2f}", f"{delta:+.2f} ({delta_pct:+.2f}%)")
            else:
                kpi1.metric("Last Price", "N/A", "0.00%")

            # KPI 2: Sentiment Score
            if not ticker_news.empty:
                avg_sent = ticker_news['sentiment'].mean()
                sent_delta = avg_sent - (ticker_news['sentiment'].iloc[1:].mean() if len(ticker_news) > 1 else 0)
                kpi2.metric("Sentiment Score", f"{avg_sent:.3f}", f"{sent_delta:+.3f}")
            else:
                kpi2.metric("Sentiment Score", "Neutral", "0.00")

            # KPI 3: Volume / Liquidity
            if not ticker_prices.empty and 'volume' in ticker_prices.columns:
                vol = ticker_prices.iloc[-1]['volume']
                kpi3.metric("Volume", f"{vol:,.0f}", help="Latest trading volume")
            else:
                kpi3.metric("Volume", "N/A")
            
            # KPI 4: News Velocity
            kpi4.metric("News Velocity", f"{len(ticker_news)} articles", "Last 24h")

            st.markdown("---")

            # --- MAIN CHART AREA ---
            tab_chart, tab_analysis, tab_macro = st.tabs(["📈 Technical Analysis", "🧠 Sentiment Analytics", "🌍 Macro View"])

            with tab_chart:
                if not ticker_prices.empty:
                    # Candlestick Chart with Subplots
                    fig = make_subplots(
                        rows=2, cols=1, 
                        shared_xaxes=True, 
                        vertical_spacing=0.01, 
                        row_heights=[0.7, 0.3],
                        specs=[[{"secondary_y": False}], [{"secondary_y": False}]]
                    )

                    # Candlesticks
                    fig.add_trace(go.Candlestick(
                        x=ticker_prices['date'],
                        open=ticker_prices['open'],
                        high=ticker_prices['high'],
                        low=ticker_prices['low'],
                        close=ticker_prices['close'],
                        name="OHLC"
                    ), row=1, col=1)

                    # Moving Averages (Optional)
                    if show_ma:
                        ma20 = ticker_prices['close'].rolling(window=20).mean()
                        ma50 = ticker_prices['close'].rolling(window=50).mean()
                        fig.add_trace(go.Scatter(x=ticker_prices['date'], y=ma20, line=dict(color='orange', width=2), name='MA 20'), row=1, col=1)
                        fig.add_trace(go.Scatter(x=ticker_prices['date'], y=ma50, line=dict(color='blue', width=2), name='MA 50'), row=1, col=1)

                    # Volume Bar
                    if show_volume and 'volume' in ticker_prices.columns:
                        colors = ['green' if row['close'] >= row['open'] else 'red' for index, row in ticker_prices.iterrows()]
                        fig.add_trace(go.Bar(
                            x=ticker_prices['date'], 
                            y=ticker_prices['volume'],
                            marker_color=colors,
                            name="Volume"
                        ), row=2, col=1)

                    fig.update_layout(
                        height=700, 
                        title=f"{selected_ticker} Price Action & Volume",
                        xaxis_rangeslider_visible=False,
                        template="plotly_dark",
                        paper_bgcolor='rgba(0,0,0,0)',
                        plot_bgcolor='rgba(0,0,0,0)'
                    )
                    st.plotly_chart(fig, use_container_width=True)
                else:
                    st.info("Insufficient price data to generate chart.")

            with tab_analysis:
                col_sent_1, col_sent_2 = st.columns([2, 1])
                
                with col_sent_1:
                    st.subheader("Sentiment Trend over Time")
                    if not ticker_news.empty:
                        # Sentiment Scatter Plot
                        fig_sent = px.scatter(
                            ticker_news, 
                            x='date', 
                            y='sentiment',
                            color='sentiment',
                            size=ticker_news['sentiment'].abs() + 0.1, # Size bubbles by intensity
                            color_continuous_scale='RdYlGn',
                            hover_data=['title', 'source'],
                            title="News Sentiment Analysis"
                        )
                        fig_sent.add_hline(y=0, line_dash="dash", line_color="white", opacity=0.5)
                        fig_sent.update_layout(template="plotly_dark", height=400)
                        st.plotly_chart(fig_sent, use_container_width=True)
                    else:
                        st.write("No sentiment data available for this period.")

                with col_sent_2:
                    st.subheader("Sentiment Distribution")
                    if not ticker_news.empty:
                        # Histogram of sentiment
                        fig_hist = px.histogram(
                            ticker_news, 
                            x="sentiment", 
                            nbins=20, 
                            color_discrete_sequence=['#636EFA'],
                            title="Polarity Distribution"
                        )
                        fig_hist.update_layout(template="plotly_dark", height=400)
                        st.plotly_chart(fig_hist, use_container_width=True)

            with tab_macro:
                st.subheader("Global Commodities & Macro Indicators")
                if not df_macro.empty:
                    # Get latest available price for each commodity
                    latest_macro = df_macro.sort_values('date').groupby('ticker').tail(1)
                    
                    fig_macro = px.bar(
                        latest_macro, 
                        x='ticker', 
                        y='close',
                        color='ticker',
                        text='close',
                        title="Real-Time Commodity Prices"
                    )
                    fig_macro.update_traces(texttemplate='$%{text:.2f}', textposition='outside')
                    fig_macro.update_layout(template="plotly_dark", height=500)
                    st.plotly_chart(fig_macro, use_container_width=True)
                else:
                    st.warning("No Macro/Commodity data found. Ensure spider targets include 'commodity' type.")

            # --- BOTTOM SECTION: RAW DATA & NEWS FEED ---
            c1, c2 = st.columns([1, 1])

            with c1:
                st.subheader("📰 Live News Feed")
                if not ticker_news.empty:
                    for i, row in ticker_news.head(10).iterrows():
                        color = "🟢" if row['sentiment'] > 0.05 else "🔴" if row['sentiment'] < -0.05 else "⚪"
                        st.markdown(f"""
                        **{row['date'].strftime('%H:%M')}** {color} [{row['source']}]  
                        _{row['title']}_
                        """, unsafe_allow_html=True)
                        st.divider()
                else:
                    st.write("No news headlines collected yet.")

            with c2:
                st.subheader("📋 Raw Data Inspector")
                with st.expander("View Underlying Dataframe"):
                    st.dataframe(ticker_prices.tail(50), height=300)

        # Pause before next refresh
        time.sleep(REFRESH_RATE)

if __name__ == "__main__":
    main()